services:
  api:
    build: ./api
    container_name: egis-api
    image: egis-api
    tty: true
    stdin_open: true
    command: ["./wait-for-it.sh", "db", "5432", "--", "uvicorn", "egis_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    # image: postgis/postgis:16-3.4
    image: 3dcitydb/3dcitydb-pg
    container_name: egis-db
    ports:
      - "5432:5432"
    volumes:
      - ./db/db-store:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: egis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SRID: 4327
      POSTGIS_SFCGAL: true # PostGIS SFCGALサポートを有効にする

  geoserver:
    image: docker.osgeo.org/geoserver:2.25.x
    container_name: egis-geoserver
    ports:
      - 8080:8080
    volumes:
      - ./geoserver/data_dir:/opt/geoserver_data
      - ./geoserver/web.xml:/opt/apache-tomcat-9.0.86/webapps/geoserver/WEB-INF/web.xml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: egis-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/webgis-app:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  wfs:
    image: 3dcitydb/wfs:latest
    container_name: egis-wfs
    ports:
      - "8081:8080"
    environment:
      CITYDB_TYPE: postgresql
      CITYDB_HOST: db
      CITYDB_PORT: 5432
      CITYDB_NAME: egis
      CITYDB_SCHEMA: citydb
      CITYDB_USERNAME: postgres
      CITYDB_PASSWORD: password
      WFS_CONTEXT_PATH: wfs
    depends_on:
      - db
