services:
  api:
    build: ./api
    container_name: egis-api
    image: egis-api
    tty: true
    stdin_open: true
    command: ["./wait-for-it.sh", "db", "5432", "--", "uvicorn", "egis_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4
    container_name: egis-db
    ports:
      - "5432:5432"
    volumes:
      - ./db/db-store:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: egis
      POSTGRES_PASSWORD: password

  geoserver:
    image: docker.osgeo.org/geoserver:2.25.x
    container_name: egis-geoserver
    ports:
      - 8080:8080
    volumes:
      - ./geoserver/data_dir:/opt/geoserver_data
      - ./geoserver/web.xml:/opt/apache-tomcat-9.0.84/webapps/geoserver/WEB-INF/web.xml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: egis-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/webgis-app:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    depends_on:
      - api
